from typing import Dict, List, Set


PERMISSION_CATALOG: List[Dict[str, str]] = [
    {
        "key": "roles.access",
        "module": "roles",
        "label": "Просмотр ролей",
        "description": "Доступ к каталогу ролей и справочнику разрешений.",
    },
    {
        "key": "roles.manage",
        "module": "roles",
        "label": "Управление ролями",
        "description": "Создание, изменение и архивация кастомных ролей.",
    },
    {
        "key": "users.access",
        "module": "users",
        "label": "Просмотр пользователей",
        "description": "Доступ к списку пользователей и их ролевым назначениям.",
    },
    {
        "key": "users.manage",
        "module": "users",
        "label": "Управление пользователями",
        "description": "Создание пользователей, смена ролей и управление архивом.",
    },
    {
        "key": "persons.access",
        "module": "persons",
        "label": "Person registry view",
        "description": "Access to Person registry, phone dedup, and linked record deep links.",
    },
    {
        "key": "persons.manage",
        "module": "persons",
        "label": "Person registry manage",
        "description": "Merge Person records and attach users, leads, and student cards.",
    },
    {
        "key": "trainer_cockpit.access",
        "module": "trainer_cockpit",
        "label": "Trainer cockpit view",
        "description": "Access to trainer cockpit summary and quick actions.",
    },
    {
        "key": "parent_dashboard.access",
        "module": "parent_dashboard",
        "label": "Parent dashboard view",
        "description": "Access to parent dashboard, weekly digest summary, questions, and web push.",
    },
    {
        "key": "personal_finance.access",
        "module": "personal_finance",
        "label": "Personal finance access",
        "description": "Access to owner personal finance workspace.",
    },
    {
        "key": "settings.access",
        "module": "settings",
        "label": "Просмотр настроек",
        "description": "Доступ к централизованным настройкам и служебным конфигурациям.",
    },
    {
        "key": "settings.manage",
        "module": "settings",
        "label": "Управление настройками",
        "description": "Изменение централизованных настроек, справочников и owner-workspace конфигурации.",
    },
    {
        "key": "communications.access",
        "module": "communications",
        "label": "Communication Hub view",
        "description": "Access to communication templates and delivery queue history.",
    },
    {
        "key": "communications.manage",
        "module": "communications",
        "label": "Communication Hub manage",
        "description": "Create and edit communication templates.",
    },
    {
        "key": "telegram.link",
        "module": "telegram",
        "label": "Telegram link access",
        "description": "Link and unlink Telegram for the current user profile.",
    },
    {
        "key": "admin_tools.manage",
        "module": "admin_tools",
        "label": "Admin tools manage",
        "description": "Run administrative maintenance tools such as trainer password reset.",
    },
    {
        "key": "reports.access",
        "module": "reports",
        "label": "Просмотр отчётов",
        "description": "Доступ к административной отчётности и аналитическим сводкам.",
    },
    {
        "key": "reports.export",
        "module": "reports",
        "label": "Экспорт отчётов",
        "description": "Выгрузка отчётов в CSV и XLSX.",
    },
    {
        "key": "b2b.access",
        "module": "b2b",
        "label": "Просмотр B2B",
        "description": "Доступ к B2B-школам, проектам, плану и связанным спискам.",
    },
    {
        "key": "b2b.manage",
        "module": "b2b",
        "label": "Управление B2B",
        "description": "Создание, изменение, импорт и удаление B2B-школ, контактов, событий и проектов.",
    },
    {
        "key": "owner_funnels.access",
        "module": "owner_funnels",
        "label": "Просмотр owner funnels",
        "description": "Доступ к owner funnels, событиям и карточкам воронок.",
    },
    {
        "key": "owner_funnels.manage",
        "module": "owner_funnels",
        "label": "Управление owner funnels",
        "description": "Создание, изменение и удаление элементов и событий owner funnels.",
    },
    {
        "key": "owner_calculations.access",
        "module": "owner_calculations",
        "label": "Просмотр owner calculations",
        "description": "Доступ к owner-модулю расчётов по тренерам.",
    },
    {
        "key": "owner_calculations.manage",
        "module": "owner_calculations",
        "label": "Управление owner calculations",
        "description": "Изменение ставок, премий и выплат в owner-модуле расчётов.",
    },
    {
        "key": "owner_dashboard.access",
        "module": "owner_dashboard",
        "label": "Просмотр owner dashboard",
        "description": "Доступ к метрическому дашборду владельца.",
    },
    {
        "key": "campaigns.access",
        "module": "campaigns",
        "label": "Просмотр campaigns",
        "description": "Доступ к кампаниям, школам кампаний, джемам и матрице школ.",
    },
    {
        "key": "campaigns.manage",
        "module": "campaigns",
        "label": "Управление campaigns",
        "description": "Создание и изменение кампаний, джемов, школ и связанных действий по матрице.",
    },
    {
        "key": "sales.access",
        "module": "sales",
        "label": "Доступ к sales-модулю",
        "description": "Маршруты и экраны sales: лиды, события, инструкции, долги и связанные операции.",
    },
    {
        "key": "finance.access",
        "module": "finance",
        "label": "Доступ к finance-модулю",
        "description": "Финансовый журнал и финансовые представления.",
    },
    {
        "key": "tasks.access",
        "module": "tasks",
        "label": "Просмотр задач",
        "description": "Доступ к модулю задач с учётом прикладной фильтрации.",
    },
    {
        "key": "tasks.manage",
        "module": "tasks",
        "label": "Управление задачами",
        "description": "Создание, редактирование и удаление задач и шаблонов.",
    },
    {
        "key": "projects.access",
        "module": "projects",
        "label": "Просмотр проектов",
        "description": "Доступ к проектам и kanban-доскам.",
    },
    {
        "key": "projects.manage",
        "module": "projects",
        "label": "Управление проектами",
        "description": "Создание проектов и изменение структуры проекта.",
    },
    {
        "key": "owner_workspace.access",
        "module": "owner_workspace",
        "label": "Доступ к owner-workspace",
        "description": "Вход в owner-workspace и его базовые разделы.",
    },
    {
        "key": "groups.access",
        "module": "groups",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ РіСЂСѓРїРї",
        "description": "Р”РѕСЃС‚СѓРї Рє СЃРїРёСЃРєСѓ РіСЂСѓРїРї Рё РёС… СЃРѕСЃС‚Р°РІСѓ СЃ СѓС‡С‘С‚РѕРј РїСЂРёРєР»Р°РґРЅРѕР№ С„РёР»СЊС‚СЂР°С†РёРё.",
    },
    {
        "key": "groups.manage",
        "module": "groups",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ РіСЂСѓРїРїР°РјРё",
        "description": "РЎРѕР·РґР°РЅРёРµ, РёР·РјРµРЅРµРЅРёРµ, Р°СЂС…РёРІР°С†РёСЏ РіСЂСѓРїРї Рё СѓРїСЂР°РІР»РµРЅРёРµ РёС… СЃРѕСЃС‚Р°РІРѕРј.",
    },
    {
        "key": "programs.access",
        "module": "programs",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ РїСЂРѕРіСЂР°РјРј",
        "description": "Р”РѕСЃС‚СѓРї Рє РєР°С‚Р°Р»РѕРіСѓ РїСЂРѕРіСЂР°РјРј Рё РёС… РјРѕРґСѓР»СЏРј СЃ СѓС‡С‘С‚РѕРј РїСЂРёРєР»Р°РґРЅРѕР№ С„РёР»СЊС‚СЂР°С†РёРё.",
    },
    {
        "key": "programs.manage",
        "module": "programs",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ РїСЂРѕРіСЂР°РјРјР°РјРё",
        "description": "РЎРѕР·РґР°РЅРёРµ, РІРµСЂСЃРёРѕРЅРёСЂРѕРІР°РЅРёРµ, Р°СЂС…РёРІР°С†РёСЏ Рё РЅР°Р·РЅР°С‡РµРЅРёРµ РїСЂРѕРіСЂР°РјРј.",
    },
    {
        "key": "abonements.access",
        "module": "abonements",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ Р°Р±РѕРЅРµРјРµРЅС‚РѕРІ",
        "description": "Р”РѕСЃС‚СѓРї Рє РєР°С‚Р°Р»РѕРіСѓ Р°Р±РѕРЅРµРјРµРЅС‚РѕРІ.",
    },
    {
        "key": "abonements.manage",
        "module": "abonements",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ Р°Р±РѕРЅРµРјРµРЅС‚Р°РјРё",
        "description": "РЎРѕР·РґР°РЅРёРµ, РёР·РјРµРЅРµРЅРёРµ, Р°СЂС…РёРІР°С†РёСЏ Рё СѓРґР°Р»РµРЅРёРµ Р°Р±РѕРЅРµРјРµРЅС‚РѕРІ.",
    },
    {
        "key": "students.access",
        "module": "students",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ СѓС‡РµРЅРёРєРѕРІ",
        "description": "Р”РѕСЃС‚СѓРї Рє СЃРїРёСЃРєСѓ СѓС‡РµРЅРёРєРѕРІ, РёС… РєР°СЂС‚РѕС‡РєР°Рј, СЃС‡РµС‚Р°Рј Рё СЃРІСЏР·Р°РЅРЅС‹Рј СЃР»СѓР¶РµР±РЅС‹Рј РґР°РЅРЅС‹Рј.",
    },
    {
        "key": "students.manage",
        "module": "students",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ СѓС‡РµРЅРёРєР°РјРё",
        "description": "РЎРѕР·РґР°РЅРёРµ, РёР·РјРµРЅРµРЅРёРµ, Р°СЂС…РёРІР°С†РёСЏ СѓС‡РµРЅРёРєРѕРІ Рё СѓРїСЂР°РІР»РµРЅРёРµ РёС… РїСЂРёРІСЏР·РєР°РјРё.",
    },
    {
        "key": "grades.access",
        "module": "grades",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ РѕС†РµРЅРѕРє",
        "description": "Р”РѕСЃС‚СѓРї Рє РѕС†РµРЅРєР°Рј, РёСЃС‚РѕСЂРёРё РѕС†РµРЅРёРІР°РЅРёСЏ Рё РїСЂРѕРіСЂРµСЃСЃСѓ СѓС‡РµРЅРёРєРѕРІ.",
    },
    {
        "key": "grades.manage",
        "module": "grades",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ РѕС†РµРЅРєР°РјРё",
        "description": "Р’С‹СЃС‚Р°РІР»РµРЅРёРµ Рё РёР·РјРµРЅРµРЅРёРµ РѕС†РµРЅРѕРє.",
    },
    {
        "key": "characteristics.access",
        "module": "characteristics",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРє",
        "description": "Р”РѕСЃС‚СѓРї Рє С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєР°Рј, СЃСЂР°РІРЅРµРЅРёСЏРј Рё РѕРїСѓР±Р»РёРєРѕРІР°РЅРЅС‹Рј РІРµСЂСЃРёСЏРј.",
    },
    {
        "key": "characteristics.manage",
        "module": "characteristics",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєР°РјРё",
        "description": "РЎРѕР·РґР°РЅРёРµ, СЂРµРґР°РєС‚РёСЂРѕРІР°РЅРёРµ, СЃРѕРіР»Р°СЃРѕРІР°РЅРёРµ Рё РїСѓР±Р»РёРєР°С†РёСЏ С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРє.",
    },
    {
        "key": "lessons.access",
        "module": "lessons",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ СѓСЂРѕРєРѕРІ",
        "description": "Р”РѕСЃС‚СѓРї Рє СЂР°СЃРїРёСЃР°РЅРёСЋ СѓСЂРѕРєРѕРІ, РєР°СЂС‚РѕС‡РєР°Рј СЃР»РѕС‚РѕРІ Рё СЃРїРёСЃРєСѓ СЂСѓС‡РЅС‹С… СѓСЂРѕРєРѕРІ.",
    },
    {
        "key": "lessons.manage",
        "module": "lessons",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ СѓСЂРѕРєР°РјРё",
        "description": "РЎРѕС…СЂР°РЅРµРЅРёРµ РїРѕСЃРµС‰Р°РµРјРѕСЃС‚Рё, РґРѕР±Р°РІР»РµРЅРёРµ СѓС‡РµРЅРёРєРѕРІ, СЃРѕР·РґР°РЅРёРµ СЃР»РѕС‚РѕРІ Рё РїРѕРґРјРµРЅР° С‚СЂРµРЅРµСЂР°.",
    },
    {
        "key": "lessons.schedule_manage",
        "module": "lessons",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ СЂР°СЃРїРёСЃР°РЅРёРµРј СѓСЂРѕРєРѕРІ",
        "description": "РџРµСЂРµРЅРѕСЃ Рё РѕС‚РјРµРЅР° СѓСЂРѕРєРѕРІ, Р° С‚Р°РєР¶Рµ РґРѕСЃС‚СѓРї Рє СЃС†РµРЅР°СЂРёСЏРј СЂСѓС‡РЅРѕРіРѕ РґРѕР±Р°РІР»РµРЅРёСЏ СѓСЂРѕРєРѕРІ.",
    },
    {
        "key": "lessons.override",
        "module": "lessons",
        "label": "Р Р°СЃС€РёСЂРµРЅРЅС‹Рµ РґРµР№СЃС‚РІРёСЏ РїРѕ СѓСЂРѕРєР°Рј",
        "description": "РЈРґР°Р»РµРЅРёРµ СѓС‡РµРЅРёРєР° РёР· СѓСЂРѕРєР° Рё РґСЂСѓРіРёРµ РѕРїРµСЂР°С†РёРё РїРѕ РёСЃРєР»СЋС‡РµРЅРёСЏРј.",
    },
    {
        "key": "student_accounts.access",
        "module": "student_accounts",
        "label": "РџСЂРѕСЃРјРѕС‚СЂ СЃС‡РµС‚РѕРІ СѓС‡РµРЅРёРєРѕРІ",
        "description": "Р”РѕСЃС‚СѓРї Рє СЃС‡РµС‚Р°Рј СѓС‡РµРЅРёРєРѕРІ Рё РёСЃС‚РѕСЂРёРё РѕРїРµСЂР°С†РёР№.",
    },
    {
        "key": "student_accounts.manage",
        "module": "student_accounts",
        "label": "РЈРїСЂР°РІР»РµРЅРёРµ СЃС‡РµС‚Р°РјРё СѓС‡РµРЅРёРєРѕРІ",
        "description": "РЎРѕР·РґР°РЅРёРµ, РёР·РјРµРЅРµРЅРёРµ, СЃРїРёСЃР°РЅРёРµ Рё СѓРґР°Р»РµРЅРёРµ СЃС‡РµС‚РѕРІ СѓС‡РµРЅРёРєРѕРІ.",
    },
    {
        "key": "student_accounts.payment",
        "module": "student_accounts",
        "label": "РџРѕРїРѕР»РЅРµРЅРёРµ СЃС‡РµС‚РѕРІ СѓС‡РµРЅРёРєРѕРІ",
        "description": "РџСЂР°РІРѕ РїСЂРѕРІРѕРґРёС‚СЊ РѕРїР»Р°С‚С‹ Рё РїРѕРїРѕР»РЅРµРЅРёСЏ РїРѕ СЃС‡РµС‚Р°Рј СѓС‡РµРЅРёРєРѕРІ.",
    },
]

VALID_PERMISSION_KEYS: Set[str] = {item["key"] for item in PERMISSION_CATALOG}
