from typing import Dict, List, Set


PERMISSION_CATALOG: List[Dict[str, str]] = [
    {
        "key": "roles.access",
        "module": "roles",
        "label": "Просмотр ролей",
        "description": "Доступ к каталогу ролей и справочнику разрешений.",
    },
    {
        "key": "roles.manage",
        "module": "roles",
        "label": "Управление ролями",
        "description": "Создание, изменение и архивация кастомных ролей.",
    },
    {
        "key": "users.access",
        "module": "users",
        "label": "Просмотр пользователей",
        "description": "Доступ к списку пользователей и их ролевым назначениям.",
    },
    {
        "key": "users.manage",
        "module": "users",
        "label": "Управление пользователями",
        "description": "Создание пользователей, смена ролей и управление архивом.",
    },
    {
        "key": "persons.access",
        "module": "persons",
        "label": "Person registry view",
        "description": "Access to Person registry, phone dedup, and linked record deep links.",
    },
    {
        "key": "persons.manage",
        "module": "persons",
        "label": "Person registry manage",
        "description": "Merge Person records and attach users, leads, and student cards.",
    },
    {
        "key": "trainer_cockpit.access",
        "module": "trainer_cockpit",
        "label": "Trainer cockpit view",
        "description": "Access to trainer cockpit summary and quick actions.",
    },
    {
        "key": "parent_dashboard.access",
        "module": "parent_dashboard",
        "label": "Parent dashboard view",
        "description": "Access to parent dashboard, weekly digest summary, questions, and web push.",
    },
    {
        "key": "passwords.access",
        "module": "passwords",
        "label": "Passwords view",
        "description": "Access to the protected password vault.",
    },
    {
        "key": "passwords.manage",
        "module": "passwords",
        "label": "Passwords manage",
        "description": "Create, edit, and delete password vault entries.",
    },
    {
        "key": "passwords.reveal",
        "module": "passwords",
        "label": "Passwords reveal",
        "description": "Reveal decrypted password vault secrets.",
    },
    {
        "key": "settings.access",
        "module": "settings",
        "label": "Просмотр настроек",
        "description": "Доступ к централизованным настройкам и служебным конфигурациям.",
    },
    {
        "key": "settings.manage",
        "module": "settings",
        "label": "Управление настройками",
        "description": "Изменение централизованных настроек, справочников и owner-workspace конфигурации.",
    },
    {
        "key": "communications.access",
        "module": "communications",
        "label": "Communication Hub view",
        "description": "Access to communication templates and delivery queue history.",
    },
    {
        "key": "communications.manage",
        "module": "communications",
        "label": "Communication Hub manage",
        "description": "Create and edit communication templates.",
    },
    {
        "key": "telegram.link",
        "module": "telegram",
        "label": "Telegram link access",
        "description": "Link and unlink Telegram for the current user profile.",
    },
    {
        "key": "admin_tools.manage",
        "module": "admin_tools",
        "label": "Admin tools manage",
        "description": "Run administrative maintenance tools such as trainer password reset.",
    },
    {
        "key": "reports.access",
        "module": "reports",
        "label": "Просмотр отчётов",
        "description": "Доступ к административной отчётности и аналитическим сводкам.",
    },
    {
        "key": "reports.export",
        "module": "reports",
        "label": "Экспорт отчётов",
        "description": "Выгрузка отчётов в CSV и XLSX.",
    },
    {
        "key": "b2b.access",
        "module": "b2b",
        "label": "Просмотр B2B",
        "description": "Доступ к B2B-школам, проектам, плану и связанным спискам.",
    },
    {
        "key": "b2b.manage",
        "module": "b2b",
        "label": "Управление B2B",
        "description": "Создание, изменение, импорт и удаление B2B-школ, контактов, событий и проектов.",
    },
    {
        "key": "owner_funnels.access",
        "module": "owner_funnels",
        "label": "Просмотр owner funnels",
        "description": "Доступ к owner funnels, событиям и карточкам воронок.",
    },
    {
        "key": "owner_funnels.manage",
        "module": "owner_funnels",
        "label": "Управление owner funnels",
        "description": "Создание, изменение и удаление элементов и событий owner funnels.",
    },
    {
        "key": "owner_calculations.access",
        "module": "owner_calculations",
        "label": "Просмотр owner calculations",
        "description": "Доступ к owner-модулю расчётов по тренерам.",
    },
    {
        "key": "owner_calculations.manage",
        "module": "owner_calculations",
        "label": "Управление owner calculations",
        "description": "Изменение ставок, премий и выплат в owner-модуле расчётов.",
    },
    {
        "key": "owner_dashboard.access",
        "module": "owner_dashboard",
        "label": "Просмотр owner dashboard",
        "description": "Доступ к метрическому дашборду владельца.",
    },
    {
        "key": "campaigns.access",
        "module": "campaigns",
        "label": "Просмотр campaigns",
        "description": "Доступ к кампаниям, школам кампаний, джемам и матрице школ.",
    },
    {
        "key": "campaigns.manage",
        "module": "campaigns",
        "label": "Управление campaigns",
        "description": "Создание и изменение кампаний, джемов, школ и связанных действий по матрице.",
    },
    {
        "key": "sales.access",
        "module": "sales",
        "label": "Доступ к sales-модулю",
        "description": "Маршруты и экраны sales: лиды, события, инструкции, долги и связанные операции.",
    },
    {
        "key": "finance.access",
        "module": "finance",
        "label": "Доступ к finance-модулю",
        "description": "Финансовый журнал и финансовые представления.",
    },
    {
        "key": "tasks.access",
        "module": "tasks",
        "label": "Просмотр задач",
        "description": "Доступ к модулю задач с учётом прикладной фильтрации.",
    },
    {
        "key": "tasks.manage",
        "module": "tasks",
        "label": "Управление задачами",
        "description": "Создание, редактирование и удаление задач и шаблонов.",
    },
    {
        "key": "projects.access",
        "module": "projects",
        "label": "Просмотр проектов",
        "description": "Доступ к проектам и kanban-доскам.",
    },
    {
        "key": "projects.manage",
        "module": "projects",
        "label": "Управление проектами",
        "description": "Создание проектов и изменение структуры проекта.",
    },
    {
        "key": "owner_workspace.access",
        "module": "owner_workspace",
        "label": "Доступ к owner-workspace",
        "description": "Вход в owner-workspace и его базовые разделы.",
    },
    {
        "key": "groups.access",
        "module": "groups",
        "label": "Просмотр групп",
        "description": "Доступ к списку групп и их составу с учётом прикладной фильтрации.",
    },
    {
        "key": "groups.manage",
        "module": "groups",
        "label": "Управление группами (всё)",
        "description": "Полный доступ ко всем действиям ниже. Даёт то же самое, что все groups.* права вместе.",
    },
    {
        "key": "groups.create",
        "module": "groups",
        "label": "Создание групп",
        "description": "Завести новую группу.",
    },
    {
        "key": "groups.edit",
        "module": "groups",
        "label": "Редактирование групп",
        "description": "Изменение группы и режима доп. занятий по слотам.",
    },
    {
        "key": "groups.delete",
        "module": "groups",
        "label": "Архивация групп",
        "description": "Архивация группы (без права на что-либо ещё из groups.manage).",
    },
    {
        "key": "groups.manage_roster",
        "module": "groups",
        "label": "Состав группы",
        "description": "Добавление и удаление учеников из группы.",
    },
    {
        "key": "groups.assign_program",
        "module": "groups",
        "label": "Назначение программ группе",
        "description": "Назначить или снять программу обучения у группы.",
    },
    {
        "key": "programs.access",
        "module": "programs",
        "label": "Просмотр программ",
        "description": "Доступ к каталогу программ и их модулям с учётом прикладной фильтрации.",
    },
    {
        "key": "programs.manage",
        "module": "programs",
        "label": "Управление программами (всё)",
        "description": "Полный доступ ко всем действиям ниже. Даёт то же самое, что все programs.* права вместе.",
    },
    {
        "key": "programs.create",
        "module": "programs",
        "label": "Создание программ",
        "description": "Завести новую программу обучения.",
    },
    {
        "key": "programs.edit",
        "module": "programs",
        "label": "Редактирование программ",
        "description": "Изменение программы, архивация/разархивация модуля или темы.",
    },
    {
        "key": "programs.assign",
        "module": "programs",
        "label": "Назначение программ",
        "description": "Назначить программу группе или ученику.",
    },
    {
        "key": "abonements.access",
        "module": "abonements",
        "label": "Просмотр абонементов",
        "description": "Доступ к каталогу абонементов.",
    },
    {
        "key": "abonements.manage",
        "module": "abonements",
        "label": "Управление абонементами",
        "description": "Создание, изменение, архивация и удаление абонементов.",
    },
    {
        "key": "students.access",
        "module": "students",
        "label": "Просмотр учеников",
        "description": "Доступ к списку учеников, их карточкам, счетам и связанным служебным данным.",
    },
    {
        "key": "students.manage",
        "module": "students",
        "label": "Управление учениками (всё)",
        "description": "Полный доступ ко всем действиям ниже. Даёт то же самое, что все students.* права вместе.",
    },
    {
        "key": "students.create",
        "module": "students",
        "label": "Создание учеников",
        "description": "Завести ученика, в т.ч. вместе с родителем; поиск родителя при создании.",
    },
    {
        "key": "students.edit",
        "module": "students",
        "label": "Редактирование учеников",
        "description": "Изменение данных ученика.",
    },
    {
        "key": "students.delete",
        "module": "students",
        "label": "Архивация учеников",
        "description": "Архивация ученика (без права на что-либо ещё из students.manage).",
    },
    {
        "key": "students.assign_program",
        "module": "students",
        "label": "Назначение программ ученику",
        "description": "Назначить или снять программу обучения у ученика.",
    },
    {
        "key": "students.invite_parent",
        "module": "students",
        "label": "Приглашение родителя",
        "description": "Сгенерировать ссылку-приглашение для родителя ученика.",
    },
    {
        "key": "grades.access",
        "module": "grades",
        "label": "Просмотр оценок",
        "description": "Доступ к оценкам, истории оценивания и прогрессу учеников.",
    },
    {
        "key": "grades.manage",
        "module": "grades",
        "label": "Управление оценками",
        "description": "Выставление и изменение оценок.",
    },
    {
        "key": "characteristics.access",
        "module": "characteristics",
        "label": "Просмотр характеристик",
        "description": "Доступ к характеристикам, сравнениям и опубликованным версиям.",
    },
    {
        "key": "characteristics.manage",
        "module": "characteristics",
        "label": "Управление характеристиками",
        "description": "Создание, редактирование, согласование и публикация характеристик.",
    },
    {
        "key": "lessons.access",
        "module": "lessons",
        "label": "Просмотр уроков",
        "description": "Доступ к расписанию уроков, карточкам слотов и списку ручных уроков.",
    },
    {
        "key": "lessons.manage",
        "module": "lessons",
        "label": "Управление уроками",
        "description": "Сохранение посещаемости, добавление учеников, создание слотов и подмена тренера.",
    },
    {
        "key": "lessons.schedule_manage",
        "module": "lessons",
        "label": "Управление расписанием уроков",
        "description": "Перенос и отмена уроков, а также доступ к сценариям ручного добавления уроков.",
    },
    {
        "key": "lessons.override",
        "module": "lessons",
        "label": "Расширенные действия по урокам",
        "description": "Удаление ученика из урока и другие операции по исключениям.",
    },
    {
        "key": "student_accounts.access",
        "module": "student_accounts",
        "label": "Просмотр счетов учеников",
        "description": "Доступ к счетам учеников и истории операций.",
    },
    {
        "key": "student_accounts.manage",
        "module": "student_accounts",
        "label": "Управление счетами учеников",
        "description": "Создание, изменение, списание и удаление счетов учеников.",
    },
    {
        "key": "student_accounts.payment",
        "module": "student_accounts",
        "label": "Пополнение счетов учеников",
        "description": "Право проводить оплаты и пополнения по счетам учеников.",
    },
    {
        "key": "seo.access",
        "module": "seo",
        "label": "SEO: просмотр",
        "description": "Доступ к разделу SEO: страницы сайта, блог, редиректы.",
    },
    {
        "key": "seo.manage",
        "module": "seo",
        "label": "SEO: управление",
        "description": "Создание, редактирование, публикация и удаление SEO-страниц и записей блога.",
    },
    {
        "key": "disk.access",
        "module": "disk",
        "label": "Disk: просмотр",
        "description": "Просмотр файлов на диске.",
    },
    {
        "key": "disk.manage",
        "module": "disk",
        "label": "Disk: управление",
        "description": "Загрузка, переименование и удаление файлов на диске.",
    },
    {
        "key": "kodex.access",
        "module": "kodex",
        "label": "Кодэкс: просмотр",
        "description": "Просмотр дел и теории в редакторе Кодэкс.",
    },
    {
        "key": "kodex.manage",
        "module": "kodex",
        "label": "Кодэкс: управление",
        "description": "Создание, редактирование и публикация дел и теории в Кодэкс.",
    },
]

VALID_PERMISSION_KEYS: Set[str] = {item["key"] for item in PERMISSION_CATALOG}
